# Generated by Django 3.0 on 2019-12-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
