# Generated by Django 3.0 on 2020-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_student_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='present',
            new_name='attendence_stat',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
