# Generated by Django 3.0 on 2020-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200102_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=True)),
            ],
        ),
    ]
