# Generated by Django 3.0 on 2020-01-06 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_attendance_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_history',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance_history',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
