# Generated by Django 3.0 on 2020-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200106_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_history',
            name='roll_no',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
